# Generated by Django 4.2.1 on 2023-05-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_forumuser_alter_forum_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumuser',
            options={'verbose_name': 'Forum User', 'verbose_name_plural': 'Forum Users'},
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
